import type { Subject } from '@/types'

export const GATE_EXAM_DATE = new Date('2027-02-07')

export const SUBJECTS: Subject[] = [
  {
    id: 'engineering-math',
    name: 'Engineering Mathematics',
    shortName: 'Eng. Math',
    color: '#6366F1',
    icon: 'math',
    chapters: [
      {
        id: 'linear-algebra',
        name: 'Linear Algebra',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Matrices & Determinants',
          'Rank & Nullity',
          'System of Linear Equations',
          'Eigenvalues & Eigenvectors',
          'Cayley-Hamilton Theorem',
          'LU Decomposition',
        ],
      },
      {
        id: 'calculus',
        name: 'Calculus',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Limits & Continuity',
          'Differentiation Rules',
          'Integration Techniques',
          'Definite & Improper Integrals',
          'Maxima & Minima',
          'Mean Value Theorems',
          'Multivariable Calculus',
        ],
      },
      {
        id: 'probability',
        name: 'Probability & Statistics',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Sample Space & Events',
          'Conditional Probability',
          "Bayes' Theorem",
          'Random Variables',
          'Probability Distributions (Binomial, Poisson, Normal)',
          'Mean, Variance & Standard Deviation',
          'Joint Distributions',
          'Sampling & Estimation',
        ],
      },
    ],
  },

  {
    id: 'digital-logic',
    name: 'Digital Logic',
    shortName: 'Digital Logic',
    color: '#10B981',
    icon: 'cpu',
    chapters: [
      {
        id: 'number-systems',
        name: 'Number Systems',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Binary, Octal & Hexadecimal',
          'Number Base Conversions',
          'Signed Number Representation',
          'Binary Arithmetic',
          'Floating Point Representation',
          'BCD & Gray Code',
        ],
      },
      {
        id: 'boolean-algebra',
        name: 'Boolean Algebra',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Boolean Laws & Identities',
          'Logic Gates (AND, OR, NOT, NAND, NOR, XOR)',
          'SOP & POS Forms',
          'Canonical Forms',
          'Karnaugh Maps (2 to 5 variables)',
          'Quine-McCluskey Method',
        ],
      },
      {
        id: 'combinational',
        name: 'Combinational Circuits',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Half & Full Adder/Subtractor',
          'Carry Lookahead Adder',
          'Multiplexers & Demultiplexers',
          'Encoders & Decoders',
          'Comparators',
          'Hazards in Combinational Circuits',
        ],
      },
      {
        id: 'sequential',
        name: 'Sequential Circuits',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Latches (SR, D)',
          'Flip-Flops (SR, JK, D, T)',
          'Flip-Flop Conversions',
          'Registers & Shift Registers',
          'Counters (Synchronous & Asynchronous)',
          'Finite State Machines (Mealy & Moore)',
          'FSM Design & Minimization',
        ],
      },
    ],
  },

  {
    id: 'computer-org',
    name: 'Computer Organization & Architecture',
    shortName: 'CO & Arch',
    color: '#F59E0B',
    icon: 'server',
    chapters: [
      {
        id: 'number-rep',
        name: 'Number Representation',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Fixed Point Representation',
          'IEEE 754 Floating Point',
          'Error Detection Codes',
          "Booth's Multiplication Algorithm",
          'Non-Restoring Division',
        ],
      },
      {
        id: 'isa',
        name: 'Instruction Set Architecture',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Instruction Formats',
          'Addressing Modes',
          'RISC vs CISC',
          'Instruction Encoding',
          'Stack vs Register Machines',
        ],
      },
      {
        id: 'datapath-alu',
        name: 'Data Path & ALU',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'ALU Design',
          'Carry Lookahead Adder',
          'Single-Cycle Data Path',
          'Multi-Cycle Data Path',
        ],
      },
      {
        id: 'control-unit',
        name: 'Control Unit',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Hardwired Control',
          'Microprogrammed Control',
          'Micro-operations',
          'Control Signals',
        ],
      },
      {
        id: 'pipelining',
        name: 'Pipelining',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Pipeline Stages',
          'Data Hazards & Forwarding',
          'Control Hazards',
          'Structural Hazards',
          'Branch Prediction',
          'Pipeline Performance Metrics',
        ],
      },
      {
        id: 'memory-hierarchy',
        name: 'Memory Hierarchy',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Cache Memory (Direct, Set-Associative, Fully Associative)',
          'Cache Replacement Policies',
          'Write Policies (Write-Through, Write-Back)',
          'Virtual Memory & Paging',
          'TLB & Page Tables',
          'Memory Interleaving',
        ],
      },
      {
        id: 'io',
        name: 'I/O Organization',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'I/O Interfaces',
          'Programmed I/O',
          'Interrupt-Driven I/O',
          'DMA (Direct Memory Access)',
          'I/O Buses',
        ],
      },
    ],
  },

  {
    id: 'prog-ds',
    name: 'Programming & Data Structures',
    shortName: 'Prog & DS',
    color: '#EF4444',
    icon: 'code',
    chapters: [
      {
        id: 'c-basics',
        name: 'C Programming',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Data Types & Operators',
          'Control Flow (Loops, Conditionals)',
          'Functions & Recursion',
          'Arrays & Strings',
          'Pointers & Pointer Arithmetic',
          'Structures & Unions',
          'Dynamic Memory Allocation',
        ],
      },
      {
        id: 'linked-lists',
        name: 'Linked Lists',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Singly Linked List',
          'Doubly Linked List',
          'Circular Linked List',
          'Linked List Operations (Insert, Delete, Search, Reverse)',
        ],
      },
      {
        id: 'stacks-queues',
        name: 'Stacks & Queues',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Stack (Array & Linked List)',
          'Queue (Array & Linked List)',
          'Circular Queue',
          'Deque (Double-Ended Queue)',
          'Priority Queue',
          'Applications (Postfix, Infix, Parenthesis)',
        ],
      },
      {
        id: 'trees',
        name: 'Trees',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Binary Trees & Traversals (Inorder, Preorder, Postorder)',
          'Binary Search Tree (BST)',
          'AVL Trees',
          'Red-Black Trees',
          'Heaps (Min-Heap, Max-Heap)',
          'B-Trees & B+ Trees',
          'Trie',
        ],
      },
      {
        id: 'graphs-ds',
        name: 'Graphs',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Graph Representation (Adjacency Matrix, List)',
          'BFS & DFS',
          'Topological Sorting',
          'Shortest Path Algorithms',
          'Minimum Spanning Tree',
        ],
      },
      {
        id: 'hashing',
        name: 'Hashing',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Hash Functions',
          'Collision Resolution (Chaining, Open Addressing)',
          'Load Factor & Rehashing',
          'Applications of Hashing',
        ],
      },
    ],
  },

  {
    id: 'algorithms',
    name: 'Algorithms',
    shortName: 'Algorithms',
    color: '#8B5CF6',
    icon: 'git-branch',
    chapters: [
      {
        id: 'analysis',
        name: 'Complexity Analysis',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Asymptotic Notation (Big-O, Omega, Theta)',
          'Best, Worst & Average Case',
          'Recurrence Relations',
          'Master Theorem',
          'Space Complexity',
        ],
      },
      {
        id: 'sorting',
        name: 'Sorting',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Bubble & Selection Sort',
          'Insertion Sort',
          'Merge Sort',
          'Quick Sort',
          'Heap Sort',
          'Counting Sort',
          'Radix Sort',
          'Stability & In-place Properties',
        ],
      },
      {
        id: 'divide-conquer',
        name: 'Divide & Conquer',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Binary Search',
          'Merge Sort Analysis',
          "Strassen's Matrix Multiplication",
          'Closest Pair of Points',
          'Quick Select',
        ],
      },
      {
        id: 'greedy',
        name: 'Greedy Algorithms',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Activity Selection Problem',
          'Huffman Coding',
          'Job Sequencing',
          "Prim's & Kruskal's MST",
          "Dijkstra's Algorithm",
          'Fractional Knapsack',
        ],
      },
      {
        id: 'dp',
        name: 'Dynamic Programming',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Memoization vs Tabulation',
          'Longest Common Subsequence (LCS)',
          'Longest Increasing Subsequence (LIS)',
          '0/1 Knapsack',
          'Matrix Chain Multiplication',
          'Edit Distance',
          'Floyd-Warshall',
          'Bellman-Ford',
        ],
      },
      {
        id: 'graph-algo',
        name: 'Graph Algorithms',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'BFS & DFS Applications',
          "Topological Sort (DFS & Kahn's)",
          'Strongly Connected Components (Tarjan, Kosaraju)',
          'Shortest Path (Dijkstra, Bellman-Ford)',
          'All-Pairs Shortest Path',
          'Network Flow (Ford-Fulkerson)',
        ],
      },
      {
        id: 'np',
        name: 'P, NP & Complexity',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'P vs NP',
          'NP-Hard & NP-Complete',
          'Polynomial Reductions',
          'SAT, Clique, Vertex Cover',
          'Approximation Algorithms',
        ],
      },
    ],
  },

  {
    id: 'theory-of-computation',
    name: 'Theory of Computation',
    shortName: 'TOC',
    color: '#EC4899',
    icon: 'zap',
    chapters: [
      {
        id: 'regular-lang',
        name: 'Regular Languages',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'DFA (Deterministic Finite Automaton)',
          'NFA & ε-NFA',
          'NFA to DFA Conversion',
          'Regular Expressions',
          'FA Minimization',
          'Closure Properties of Regular Languages',
          'Pumping Lemma for Regular Languages',
        ],
      },
      {
        id: 'cfg',
        name: 'Context-Free Languages',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Context-Free Grammars (CFG)',
          'Parse Trees & Derivations',
          'Ambiguity in CFGs',
          'Simplification (CNF, GNF)',
          'Closure Properties of CFLs',
          'Pumping Lemma for CFLs',
        ],
      },
      {
        id: 'pda',
        name: 'Pushdown Automata',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Deterministic PDA (DPDA)',
          'Non-Deterministic PDA (NPDA)',
          'PDA to CFG Conversion',
          'CFG to PDA Conversion',
        ],
      },
      {
        id: 'turing',
        name: 'Turing Machines',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Basic Turing Machine Model',
          'TM Design',
          'Multi-Tape Turing Machines',
          'Non-Deterministic TM',
          'Universal Turing Machine',
          'Church-Turing Thesis',
        ],
      },
      {
        id: 'decidability',
        name: 'Decidability',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Recursive & Recursively Enumerable Languages',
          'Halting Problem',
          "Rice's Theorem",
          'Reductions',
          'Undecidable Problems',
        ],
      },
      {
        id: 'complexity',
        name: 'Complexity Classes',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Time & Space Complexity of TMs',
          'P Class',
          'NP Class',
          'NP-Hard & NP-Complete',
          'co-NP',
          'PSPACE',
        ],
      },
    ],
  },

  {
    id: 'compiler-design',
    name: 'Compiler Design',
    shortName: 'Compiler',
    color: '#14B8A6',
    icon: 'terminal',
    chapters: [
      {
        id: 'lexical',
        name: 'Lexical Analysis',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Tokens, Lexemes & Patterns',
          'Regular Expressions for Tokens',
          'RE to NFA (Thompson)',
          'NFA to DFA (Subset Construction)',
          'DFA Minimization',
          'Lex Tool',
        ],
      },
      {
        id: 'parsing',
        name: 'Syntax Analysis (Parsing)',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Context-Free Grammars for PL',
          'Top-Down Parsing (Recursive Descent)',
          'LL(1) Parsing & Parse Tables',
          'FIRST & FOLLOW Sets',
          'Bottom-Up Parsing (Shift-Reduce)',
          'LR(0) & SLR(1) Parsing',
          'CLR(1) & LALR(1) Parsing',
          'YACC Tool',
        ],
      },
      {
        id: 'semantic',
        name: 'Semantic Analysis',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Symbol Table Organization',
          'Scope & Binding',
          'Type Checking',
          'Syntax-Directed Definitions',
          'Attribute Grammars',
        ],
      },
      {
        id: 'intermediate',
        name: 'Intermediate Code Generation',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Three-Address Code',
          'Quadruples, Triples & Indirect Triples',
          'DAG Representation',
          'Translation of Expressions',
          'Boolean Expression Translation',
        ],
      },
      {
        id: 'optimization',
        name: 'Code Optimization',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Local Optimization',
          'Common Subexpression Elimination',
          'Dead Code Elimination',
          'Loop Optimization',
          'Constant Folding & Propagation',
          'Data Flow Analysis',
        ],
      },
      {
        id: 'code-gen',
        name: 'Code Generation',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Register Allocation',
          'Instruction Selection',
          'Peephole Optimization',
          'Target Machine Model',
        ],
      },
    ],
  },

  {
    id: 'operating-systems',
    name: 'Operating Systems',
    shortName: 'OS',
    color: '#F97316',
    icon: 'layers',
    chapters: [
      {
        id: 'processes',
        name: 'Process Management',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Process States & PCB',
          'Process Creation & Termination',
          'Context Switching',
          'Threads (User-level vs Kernel-level)',
          'Multithreading Models',
          'Inter-Process Communication (IPC)',
        ],
      },
      {
        id: 'scheduling',
        name: 'CPU Scheduling',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Scheduling Criteria (CPU utilization, Throughput, Turnaround)',
          'FCFS & SJF',
          'SRTF (Preemptive SJF)',
          'Round Robin',
          'Priority Scheduling',
          'Multilevel Queue & Multilevel Feedback Queue',
          'Scheduling Numericals',
        ],
      },
      {
        id: 'sync',
        name: 'Process Synchronization',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Race Condition & Critical Section',
          'Mutex Locks',
          'Semaphores (Binary & Counting)',
          'Classic Problems (Dining Philosophers, Producer-Consumer, Readers-Writers)',
          'Monitors',
          'Condition Variables',
        ],
      },
      {
        id: 'deadlocks',
        name: 'Deadlocks',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Necessary Conditions (Coffman)',
          'Resource Allocation Graph',
          'Deadlock Prevention',
          "Deadlock Avoidance (Banker's Algorithm)",
          'Deadlock Detection',
          'Recovery from Deadlock',
        ],
      },
      {
        id: 'memory-mgmt',
        name: 'Memory Management',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Contiguous Allocation',
          'Paging',
          'Segmentation',
          'Segmentation with Paging',
          'Internal & External Fragmentation',
          'Compaction',
        ],
      },
      {
        id: 'virtual-memory',
        name: 'Virtual Memory',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Demand Paging',
          'Page Fault & Handling',
          "Page Replacement (FIFO, LRU, Optimal, LFU)",
          "Belady's Anomaly",
          'Thrashing',
          'Working Set Model',
        ],
      },
      {
        id: 'file-systems',
        name: 'File Systems',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'File Concepts & Access Methods',
          'Directory Structure',
          'Allocation Methods (Contiguous, Linked, Indexed)',
          'Inodes',
          'Disk Scheduling (FCFS, SSTF, SCAN, C-SCAN)',
          'RAID',
        ],
      },
    ],
  },

  {
    id: 'databases',
    name: 'Databases',
    shortName: 'DBMS',
    color: '#06B6D4',
    icon: 'database',
    chapters: [
      {
        id: 'er-model',
        name: 'ER Model',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Entities & Attributes',
          'Relationships & Cardinality',
          'ER Diagrams',
          'Extended ER (EER)',
          'ER to Relational Mapping',
        ],
      },
      {
        id: 'relational',
        name: 'Relational Model',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Keys (Super, Candidate, Primary, Foreign)',
          'Relational Algebra (σ, π, ⋈, ×, ∪, −)',
          'Tuple Relational Calculus',
          'Domain Relational Calculus',
          'Integrity Constraints',
        ],
      },
      {
        id: 'sql',
        name: 'SQL',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'DDL (CREATE, ALTER, DROP)',
          'DML (INSERT, UPDATE, DELETE)',
          'SELECT & WHERE Clauses',
          'Joins (Inner, Outer, Self, Cross)',
          'Aggregation & GROUP BY',
          'Subqueries & Nested Queries',
          'Views & Indexes',
        ],
      },
      {
        id: 'normalization',
        name: 'Normalization',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Functional Dependencies',
          "Armstrong's Axioms",
          'Closure of Attributes',
          '1NF, 2NF, 3NF',
          'BCNF',
          'Lossless Decomposition',
          'Dependency Preservation',
        ],
      },
      {
        id: 'transactions',
        name: 'Transactions & Concurrency',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'ACID Properties',
          'Transaction States',
          'Serializability (Conflict & View)',
          'Two-Phase Locking (2PL)',
          'Timestamp-Based Protocols',
          'Deadlocks in DBMS',
          'Recovery (Log-Based, Shadow Paging)',
        ],
      },
      {
        id: 'indexing',
        name: 'Indexing & Hashing',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Primary, Secondary & Clustering Indexes',
          'Dense & Sparse Indexes',
          'B+ Tree Index',
          'Static & Dynamic Hashing',
          'Query Optimization Overview',
        ],
      },
    ],
  },

  {
    id: 'computer-networks',
    name: 'Computer Networks',
    shortName: 'CN',
    color: '#84CC16',
    icon: 'wifi',
    chapters: [
      {
        id: 'network-models',
        name: 'Network Models',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'OSI Model (7 Layers)',
          'TCP/IP Model',
          'Protocol Encapsulation',
          'Network Devices (Hub, Switch, Router, Gateway)',
        ],
      },
      {
        id: 'data-link',
        name: 'Data Link Layer',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Framing',
          'Error Detection (CRC, Checksum, Parity)',
          'Error Correction (Hamming Code)',
          'Flow Control (Stop-and-Wait, Go-Back-N, Selective Repeat)',
          'MAC Protocols (ALOHA, CSMA/CD, CSMA/CA)',
          'Ethernet & IEEE 802.3',
          'Sliding Window Protocol',
        ],
      },
      {
        id: 'network-layer',
        name: 'Network Layer',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'IPv4 Addressing & Subnetting',
          'CIDR & VLSM',
          'IPv6 Basics',
          'Routing Algorithms (Distance Vector, Link State)',
          'RIP, OSPF & BGP',
          'NAT & PAT',
          'ICMP',
          'ARP & RARP',
        ],
      },
      {
        id: 'transport',
        name: 'Transport Layer',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'UDP',
          'TCP (Connection Establishment & Termination)',
          'TCP Flow Control (Sliding Window)',
          'TCP Congestion Control (Slow Start, AIMD)',
          'TCP Error Control',
          'Port Numbers & Sockets',
        ],
      },
      {
        id: 'application',
        name: 'Application Layer',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'HTTP & HTTPS',
          'FTP & TFTP',
          'DNS (Resolution, Records)',
          'SMTP, POP3 & IMAP',
          'DHCP',
          'SNMP',
        ],
      },
      {
        id: 'network-security',
        name: 'Network Security',
        zeroWeightTopics: ['Basics'],
        topics: [
          'Basics',
          'Symmetric Cryptography (DES, AES)',
          'Asymmetric Cryptography (RSA)',
          'Digital Signatures',
          'SSL/TLS',
          'Firewalls & IDS',
          'VPN',
        ],
      },
    ],
  },
]